# Site settings
author: Benjamin Parish
title: Ben's Traverse to Tech
header-img: img/home-bg.png
email: parishben13@gmail.com
copyright_name: Benjamin Parish
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School - Software Engineer Track
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: bpar1318
github_username:  ParishBen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
